name: replace-header-gts-09-02-2020 
namespace: com.citrix.adc.stylebooks
version: "1.0"
display-name: Request Header Replacement StyleBook
private: true
schema-version: "1.0"
description: |    
    This StyleBook replaces an HTTP header in the request or response stream. For each header, the user 
    specifies the header name and the new header value, and optionally a Citrix ADC Policy expression for selecting a subset of the requests    
    for which the header is replaced (defaults to "true" which means the header is replaced in all requests or responses).
import-stylebooks: 
  - 
    namespace: netscaler.nitro.config
    version: "13.0"
    prefix: ns
  - 
    namespace: com.citrix.adc.commontypes
    version: "1.0"
    prefix: cmtypes
substitutions:
  replace-expr(onresponse, header): if-then-else($onresponse == true, str("HTTP.RES.HEADER(%{quotewrap($header)}%)"), str("HTTP.REQ.HEADER(%{quotewrap($header)}%)"))
parameters:
    -
        name: appname
        type: string
        label: Application Name
        required: true
        description: The Name of the Application
    -
        name: header
        type: object
        description: The header to insert
        parameters-default-sources:
            - cmtypes::replace-header-params-gts-09-02-2020 
components:
  -
    name: replace-header-action-comp
    type: ns::rewriteaction
    properties:
        name: $parameters.appname + "-pr-" + str($parameters.header.priority) + "-rewrite-action"
        type: REPLACE
        target: $substitutions.replace-expr($parameters.header.on-response, $parameters.header.name) 
        stringbuilderexpr: str("\"") + $parameters.header.value + str("\"")
    components:
      -
        name: replace-header-policy-comp
        type: ns::rewritepolicy
        properties:
            name: $parameters.appname + "-pr-" + str($parameters.header.priority) + "-rewrite-policy"
            rule: $parameters.header.pattern
            action: $parent.properties.name

outputs:
    -
        name: replace-header-policy
        value: $components.replace-header-action-comp.components.replace-header-policy-comp