--- 
components: 
  - 
    name: snip-be
    properties: 
      ipaddress: "ip($parameters.lb-virtual-ip) + ip(0.0.2.0)"
      netmask: str(255.255.254.0)
      type: snip
    type: "ns::nsip"
  - 
    name: netprof-comp
    properties: 
      name: "$parameters.appname + \"-netprof\""
      srcip: str($components.snip-be.properties.ipaddress)
      srcippersistency: ENABLED
    type: "ns::netprofile"
  - 
    description: "This list of components are used to generate LB Vservers for all the pools used in Content Switching (L7 rules supplied in parameters)"
    name: lb-mon-comps
    properties: 
      netprofile-param: $components.netprof-comp.properties.name
      owner: str(template)
    properties-default-sources: 
      - $parameters
    type: "stlb::lb-mon-full-final-gts-09-02-2020"
  - 
    components: 
      - 
        name: lb-bot-policy-binding
        properties: 
          bindpoint: REQUEST
          name: $components.lb-mon-comps.outputs.lbvserver-name
          policyname: $parent.outputs.bot-policy-name
          priority: 100
        type: "ns::lbvserver_botpolicy_binding"
    condition: "$parameters.lb-service-type == str(\"SSL\") OR $parameters.lb-service-type == str(\"HTTP\")"
    description: "This creates bot management profile and policy to protect application."
    name: app-sec-bot-policy-comp
    properties: 
      appname: "$parameters.appname + \"-\" + $substitutions.lb-virtual-port($parameters.lb-virtual-port)"
    properties-default-sources: 
      - $parameters
    type: "stlb::bot-profile-gts-09-02-2020"
description: "This StyleBook defines a single-port VIP Application configuration"
display-name: "Single-port Load Balancing APP StyleBook with L7 Features"
import-stylebooks: 
  - 
    namespace: netscaler.nitro.config
    prefix: ns
    version: "13.0"
  - 
    namespace: com.citrix.adc.stylebooks
    prefix: stlb
    version: "1.0"
  - 
    namespace: com.citrix.adc.commontypes
    prefix: cmtypes
    version: "1.0"
name: template-single-lb-mon-gts-09-02-2020
namespace: com.citrix.adc.stylebooks
operations: 
  analytics: 
    - 
      name: lbvserver-ops-comp1
      properties: 
        filter: "true"
        insights: 
          - 
            type: webinsight
          - 
            type: securityinsight
        target: $components.lb-mon-comps.outputs.lbvserver-comp-final
parameters-default-sources: 
  - "cmtypes::app-params-gts-09-02-2020"
  - "cmtypes::lbvserver-params-gts-09-02-2020"
  - "cmtypes::services-params-gts-09-02-2020"
  - "cmtypes::certificate-param-gts-09-02-2020"
  - "cmtypes::rewrite-config-params-gts-09-02-2020"
  - "cmtypes::responder-config-params-gts-09-02-2020"
  - "cmtypes::ssl-config-params-gts-09-02-2020"
  - "cmtypes::protection-param-gts-09-02-2020"
  - "cmtypes::bot-profile-params-gts-09-02-2020"
schema-version: "1.0"
substitutions: 
  lb-virtual-port(lb-virtual-port): "if-then-else($lb-virtual-port == \"*\",str(ANY),str($lb-virtual-port))"
version: "1.0"
